/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package listaDepartementos.Presentacion;

import entrega.pkg2.Empleado;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class mostrarEmpleados extends javax.swing.JDialog {

    /**
     * Creates new form mostrarEmpleados
     */
    public mostrarEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/images/empresa.png")).getImage());
        } catch (Exception e) {
            System.out.println("Error al cargar");
        }
        this.empresa=empresa;
        this.ventanaPrincipal=ventana;
        this.empreados=departamento.verEmpleados();
        this.llenarTabla();
    }
    public void llenarTabla(){
    DefaultTableModel modelTabla=new DefaultTableModel(new String[]{"ID","Tipo" "Usuario","Contraseña"},this.empleados.size()); 
}   this.TablaEmpleados.setModel(modelTabla);
     TableMoedel DatosUsuarios=TablaEmpleados.getModel();
     for  (int i=0;i<this.empleados.size(); i++) {
     Empleado emp=this.empleados.get(i);
     datosModel.setValueAT(emp.getId(),i,0);
     datosModel.setValueAT(emp.getTipo(),i,1);
     datosModel.setValueAT(emp.getUsuario(),i,2);
     datosModel.setValueAT(emp.getContraseña(),i,3);
     datosModel.setValueAT(emp.getNombretId(),i,4);

    }
   }
    

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        tbnActualizar = new javax.swing.JButton();
        ID = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setText("Mostrar Empleados");

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tbnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbnActualizar.setText("Actualizar");
        tbnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnActualizarActionPerformed(evt);
            }
        });

        ID.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Usuario", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        ID.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(157, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnEliminar)
                .addGap(100, 100, 100)
                .addComponent(tbnActualizar)
                .addGap(100, 100, 100)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(tbnActualizar)
                    .addComponent(btnVolver))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila=this.TablaEmpleados.getSelectedRow();
        if (fila>=0){
        Empleado emp=this.empleados.get(fila); 
        int Eliminar =JOptionPane.showConfirmDialog(this, +"Eliminar:"  emp.getNombre());
        if(Eliminar==0) {
        this.departamento(emp.getId());
        this.empleados=this.departamento.verEmpleado();
        this.llenarTabla();
}else{
        JOptionPane.showMessageDialog(this,"Seleccionar Empleado" emp);
}
        String nombreBuscar=this.texNommbreBuscar.getText();
        Empleado emp=this.departamento.buscarEmpleado(nombreBuscar);
        if(emp==null)
        JOptionPane.showMessageDialog(this,"el empleado"+nombreBuscar+"no se encontro");
        }else{
            JOptionPane.showConfirmDialog(this,"El empleado es"+ nombre);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tbnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ID;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tbnActualizar;
    // End of variables declaration//GEN-END:variables

